### ISSUE TITLE
Malformed README.md markdown

### ISSUE THREAD

**Issue by ikescanuser** [royhills/ike-scan#21] opened 2017-07-25 18:05 UTC
After the https://github.com/royhills/ike-scan#ike-packet-details section, the rest of the document is marked as code, so any further sections have invalid links e.g. https://github.com/royhills/ike-scan#backoff-fingerprinting

**Comment by royhills** [comment] 2017-07-25 18:16
Thanks for pointing this out.  It was caused by an inadvertand linebreak in README.md.
Fixed in 812e141cf3849a9d59a612e5e94ad53664e659a1

**Closed** 2017-07-25 20:34 UTC
